# Generated by Django 4.2.1 on 2023-05-25 13:54

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('provincial_organization', models.PositiveIntegerField(verbose_name='Provincial Organization')),
                ('provincial_prison', models.PositiveIntegerField(verbose_name='Provincial Prison')),
                ('state', django_fsm.FSMField(choices=[('ST', 'Starting'), ('CO', 'Completed')], default='ST', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
