# Generated by Django 4.2.1 on 2023-06-02 19:13

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincial_organization', models.PositiveIntegerField(verbose_name='Provincial Organization')),
                ('provincial_prison', models.PositiveIntegerField(verbose_name='Provincial Prison')),
                ('state', django_fsm.FSMField(choices=[('CT', 'Created'), ('PR', 'Processing'), ('CO', 'Completed')], default='CT', max_length=50)),
            ],
        ),
    ]
