# Generated by Django 4.2.1 on 2023-05-25 15:21

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='state',
            field=django_fsm.FSMField(choices=[('CT', 'Created'), ('PR', 'Processing'), ('CO', 'Completed')], default='CT', max_length=50),
        ),
    ]
